In [68]:
greetings = "Assalam-o-Alaikum!"
print(greetings)

Assalam-o-Alaikum!


### Import Libraries

In [69]:
import pandas as pd
import numpy as np
from tensorflow import constant, Variable, add, ones, matmul, multiply, ones_like, reduce_sum, GradientTape, keras
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("uci_credit_card.csv")
df[:5]

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

### Constant

In [4]:
credit_numpy = df[["EDUCATION","MARRIAGE", "AGE", "BILL_AMT1"]]

# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)
credit_constant[:3]

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[2.0000e+00, 1.0000e+00, 2.4000e+01, 3.9130e+03],
       [2.0000e+00, 2.0000e+00, 2.6000e+01, 2.6820e+03],
       [2.0000e+00, 2.0000e+00, 3.4000e+01, 2.9239e+04]])>

In [5]:
credit_constant.shape

TensorShape([30000, 4])

In [6]:
credit_constant.dtype

tf.float64

### Variables

In [7]:
A1 = Variable([1, 2, 3, 4])
print(A1)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>


In [8]:
# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()
B1

array([1, 2, 3, 4])

### Basic Operations

In [9]:
# 0-dimensional tensors

A0 = constant([1])
B0 = constant([2])

# 1-dimensional tensors

A1 = constant([1, 2])
B1 = constant([3, 4])

# 2-dimensional tensors
A2 = constant([[1, 2], [3, 4]])
B2 = constant([[5, 6], [7, 8]])

In [10]:
# Perform tensor addition with add()
C0 = add(A0, B0)
C1 = add(A1, B1)
C2 = add(A2, B2)

print(C0, "\n")
print(C1, "\n")
print(C2)

tf.Tensor([3], shape=(1,), dtype=int32) 

tf.Tensor([4 6], shape=(2,), dtype=int32) 

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


### Element-Wise Multiplication

In [11]:
# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define tensors A1 and A23 as constants
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23, B23)

In [12]:
C1.numpy()

array([1, 2, 3, 4])

In [13]:
C23.numpy()

array([[1, 2, 3],
       [1, 6, 4]])

### Making Predictions with Matrix Multiplication

In [14]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])

params = constant([[1000], [150]])

bill = constant([[3913], [2682], [8617], [64400]])

In [15]:
# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


### Optimizing with Gradients

In [16]:
def compute_gradient(x0):
    x = Variable(x0)
    
    with GradientTape() as tape:
        tape.watch(x)
        
        y = x * x
    
    return tape.gradient(y, x).numpy()

# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


### Import and Convert Data

In [66]:
housing = pd.read_csv("kc_house_data.csv")
housing[:5]

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

### Linear Regression in Tensorflow

In [67]:
price = np.array(housing['price'], np.float32)
size = np.array(housing['sqft_living'], np.float32)

In [68]:
# Convert into Natural Logarithm
price_log = np.log(price)
size_log = np.log(size)

**Loss Function**

In [69]:
def linear_regression(intercept, slope, feature):
    return intercept + feature * slope

def loss_function(intercept, slope, target = price_log, feature = size_log):
    predictions = linear_regression(intercept, slope, feature)
    return tf.keras.losses.mse(target, predictions)

In [70]:
# Compute the loss for different slope and intercept values
print(loss_function(0.1, 0.1).numpy())
print(loss_function(0.1, 0.5).numpy())

148.91295
84.309


In [71]:
# Initialize an adam optimizer
opt = keras.optimizers.Adam(0.5)

for j in range(100):
    # Apply minimize, pass the loss function, and supply the variables
    opt.minimize(lambda: loss_function(intercept, slope), var_list=[intercept, slope])

    # Print every 10th value of the loss
    if j % 10 == 0:
        print(loss_function(intercept, slope).numpy())

18.332563
2.6989741
1.7044154
0.3462424
0.19850084
0.20210081
0.19723512
0.19537346
0.19564094
0.19395621


### The linear algebra of dense layers

In [85]:
credit_card = pd.read_csv("uci_credit_card.csv")
credit_card[:5]

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [97]:
subset = np.array(credit_card[["EDUCATION", "MARRIAGE", "AGE"]], np.float32)

In [84]:
bias1 = Variable(1.0)
weights1 = Variable(ones((3, 2)))
product1 = matmul(subset, weights1)
dense1 = keras.activations.sigmoid(product1 + bias1)

print("\n dense1's output shape: {}".format(dense1.shape))


 dense1's output shape: (30000, 2)


In [86]:
# Initialize bias2 and weights2
bias2 = Variable(1.0)
weights2 = Variable(ones((2, 1)))
product2 = matmul(dense1, weights2)
dense2 = keras.activations.sigmoid(product2 + bias2)
prediction = keras.activations.sigmoid(product2 + bias2)
print('\n prediction: {}'.format(prediction.numpy()[0,0]))
print('\n actual: 1')


 prediction: 0.9525741338729858

 actual: 1


### Using the dense layer operation

In [88]:
# Define the first dense layer
dense1 = keras.layers.Dense(7, activation = 'sigmoid')(subset)

# Define a dense layer with 3 output nodes
dense2 = keras.layers.Dense(3, activation = 'sigmoid')(dense1)

# Define a dense layer with 1 output node
predictions = keras.layers.Dense(1, activation = 'sigmoid')(dense2)

# Print the shapes of dense1, dense2, and predictions
print('\n shape of dense1: ', dense1.shape)
print('\n shape of dense2: ', dense2.shape)
print('\n shape of predictions: ', predictions.shape)


 shape of dense1:  (30000, 7)

 shape of dense2:  (30000, 3)

 shape of predictions:  (30000, 1)


### Binary Classification Problems

In [86]:
bill_amounts = credit_card[["PAY_AMT4", "PAY_AMT5", "PAY_AMT6"]]

In [90]:
# Construct input layer from features
inputs = constant(bill_amounts, np.float32)

# Define first dense layer
dense1 = keras.layers.Dense(3, activation = 'relu')(inputs)

# Define second dense layer
dense2 = keras.layers.Dense(2, activation = 'relu')(dense1)

# Define output layer
output = keras.layers.Dense(1, activation = 'sigmoid')(dense2)

pd.DataFrame({"Actual": credit_card["default.payment.next.month"],
              "Predicted": outputs})[::20]

Actual  Predicted
0           1          1
20          0          0
40          0          0
60          1          1
80          0          0
...       ...        ...
29900       1          1
29920       1          1
29940       0          0
29960       0          0
29980       0          0

[1500 rows x 2 columns]

### Multiclass classification problems

In [91]:
features = credit_card[["SEX", "MARRIAGE", "AGE", "PAY_2", "BILL_AMT5", "PAY_AMT4"]]

# Construct input layer from borrower features
inputs = constant(features, np.float32)

# Define first dense layer
dense1 = keras.layers.Dense(10, activation = 'sigmoid')(inputs)

# Define second dense layer
dense2 = keras.layers.Dense(8, activation = 'relu')(dense1)

# Define output layer
outputs = keras.layers.Dense(6, activation = 'softmax')(dense2)

# Print first five predictions
print(outputs.numpy()[:5])

[[0.0922778  0.20719923 0.14760678 0.13216747 0.19903319 0.22171555]
 [0.10697705 0.22005339 0.16594997 0.0960363  0.18593487 0.22504845]
 [0.10697705 0.22005339 0.16594997 0.0960363  0.18593487 0.22504845]
 [0.10697705 0.22005339 0.16594997 0.0960363  0.18593487 0.22504845]
 [0.09032568 0.21949975 0.15278225 0.10855717 0.19676611 0.23206906]]


In [96]:
# Initialize variables in Tensorflow
weights = tf.Variable(tf.random.normal([500, 500]))

bias = tf.Variable(tf.random.truncated_normal([500, 500]))

dense1 = tf.keras.layers.Dense(32, activation = 'relu')

dense2 = tf.keras.layers.Dense(32, activation  = 'relu', kernel_initializer = 'zeros')

In [98]:
inputs = np.array(subset, np.float32)

dense1 = keras.layers.Dense(32, activation = 'relu')(inputs)

dense2 = keras.layers.Dense(16, activation = 'relu')(dense1)

dropout = keras.layers.Dropout(0.25)(dense2)

outputs = keras.layers.Dense(1, activation = 'sigmoid')(dropout)

### Initialization in TensorFlow

In [116]:
# Define the layer 1 weights
w1 =Variable(np.random.normal([23, 7]))

# Initialize the layer 1 bias
b1 = Variable(ones([7]))

# Define the layer 2 weights
w2 = Variable(np.random.normal([7, 1]))

# Define the layer 2 bias
b2 =Variable([0.0])

### Defining the model and loss function

In [117]:
# defining the model
def model(w1, b1, w2, b2, features = subset):
    # Apply relu activation functions to layer 1
    layer1 = keras.activations.relu(matmul(features, w1) + b1)
    
    # Apply Dropout
    dropout = keras.layers.Dropout(0.25)(layer1)
    return keras.activations.sigmoid(matmul(dropout, w2) + b2)

# Define the loss function
def loss_function(w1, b1, w2, b2, features = subset, target = credit_card["default.payment.next.month"]):
    predictions = model(w1, b1, w2, b2)
    
    # Pass targets and predictions to the cross entropy loss
    return keras.losses.binary_crossentropy(target, predictions)

### Building a Sequential Model

In [127]:
images = pd.read_csv("slmnist.csv")
images[:5]

1  142  143  146  148  149  149.1  149.2  150  151  ...  0.1   15   55  \
0  0  141  142  144  145  147    149    150  151  152  ...  173  179  179   
1  1  156  157  160  162  164    166    169  171  171  ...  181  197  195   
2  3   63   26   65   86   97    106    117  123  128  ...  175  179  180   
3  1  156  160  164  168  172    175    178  180  182  ...  108  107  106   
4  0  159  163  167  168  170    173    175  178  178  ...  173  233  235   

    63  37.2  61.1  77.2  65.1  38.1   23  
0  180   181   181   182   182   183  183  
1  193   193   191   192   198   193  182  
2  182   183   183   184   185   185  185  
3  110   111   108   108   102    84   70  
4  235   236   235   235   236   235  235  

[5 rows x 785 columns]

In [126]:
model = keras.Sequential()

model.add(keras.layers.Dense(16, activation = 'relu', input_shape = (28*28,)))

model.add(keras.layers.Dense(8, activation = 'relu'))

model.add(keras.layers.Dropout(0.25))

model.add(keras.layers.Dense(4, activation = 'softmax'))

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

model.fit(features, target, epochs = 10, validation_split=0.10)

print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_64 (Dense)             (None, 16)                12560     
_________________________________________________________________
dense_65 (Dense)             (None, 8)                 136       
_________________________________________________________________
dropout_2 (Dropout)          (None, 8)                 0         
_________________________________________________________________
dense_66 (Dense)             (None, 4)                 36        
Total params: 12,732
Trainable params: 12,732
Non-trainable params: 0
_________________________________________________________________
None


### Two Input Models

In [125]:
model1_inputs = keras.Input(shape = (28*28,))

model2_inputs = keras.Input(shape = (10,))


model1_layer1 = keras.layers.Dense(12, activation = 'relu')(model1_inputs)
model1_layer2 = keras.layers.Dense(4, activation = 'softmax')(model1_layer1)

model2_layer1 = keras.layers.Dense(8, activation = 'relu')(model2_inputs)
model2_layer2 = keras.layers.Dense(4, activation = 'softmax')(model2_layer1)

merged = keras.layers.add([model1_layer2, model2_layer2])

model = keras.Model(inputs = [model1_inputs, model2_inputs], outputs = merged)

model.compile('adam', loss = 'categorical_crossentropy')

# Print a model summary
print(model.summary())

Model: "functional_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 784)]        0                                            
__________________________________________________________________________________________________
input_4 (InputLayer)            [(None, 10)]         0                                            
__________________________________________________________________________________________________
dense_60 (Dense)                (None, 12)           9420        input_3[0][0]                    
__________________________________________________________________________________________________
dense_62 (Dense)                (None, 8)            88          input_4[0][0]                    
_______________________________________________________________________________________

### Training models with the Estimators API

In [133]:
size = tf.feature_column.numeric_column("size")

In [134]:
rooms = tf.feature_column.categorical_column_with_vocabulary_list("rooms", ["1", "2", "3", "4", "5"])

In [135]:
features_list = [size, rooms]

In [136]:
def input_fn():
    features = {"size": [1340, 1690, 2720], "rooms": [1, 3, 4]}
    labels = [221900, 538000, 180000]
    return features, labels